name: voice_message_player
description: Flutter package to play/puase voice message in chat messengers.
version: 1.1.1
homepage: https://github.com/Moeed366/

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  just_audio: ^0.9.37
  syncfusion_flutter_calendar: ^31.1.19 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


